### ISSUE TITLE
change this to meet requirements of LF

### ISSUE THREAD

**Issue by PaulCharlton** [apptainer/container-library-client#3]
https://github.com/apptainer/container-library-client/blob/2ec9942adfeebd0f390b22f8c29f153707bb9e90/client/client.go#L49

@DrDaveD

**Comment by DrDaveD** [comment]
The trouble is we don't necessarily have another good default.  I'm currently expecting to override the default on the apptainer side so there is no default, so people will be required to specify their default server.  I don't think it necessarily needs to be that way in the library too, but maybe it does.

**Comment by PaulCharlton** [comment]
@DrDaveD this is an LF compliance issue.   better to set it to "library.example.com" in the source code than to point to a commercial server.

**Comment by ikaneshiro** [comment]
I would recommend removing the default url all together and returning an error if one is not set
